package io.github.erp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstitutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstitutionAllPropertiesEquals(Institution expected, Institution actual) {
        assertInstitutionAutoGeneratedPropertiesEquals(expected, actual);
        assertInstitutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstitutionAllUpdatablePropertiesEquals(Institution expected, Institution actual) {
        assertInstitutionUpdatableFieldsEquals(expected, actual);
        assertInstitutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstitutionAutoGeneratedPropertiesEquals(Institution expected, Institution actual) {
        assertThat(expected)
            .as("Verify Institution auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstitutionUpdatableFieldsEquals(Institution expected, Institution actual) {
        assertThat(expected)
            .as("Verify Institution relevant properties")
            .satisfies(e -> assertThat(e.getInstitutionName()).as("check institutionName").isEqualTo(actual.getInstitutionName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstitutionUpdatableRelationshipsEquals(Institution expected, Institution actual) {
        assertThat(expected)
            .as("Verify Institution relationships")
            .satisfies(e -> assertThat(e.getParentInstitution()).as("check parentInstitution").isEqualTo(actual.getParentInstitution()));
    }
}
